config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  resource :sessions, only: [:new, :create, :destroy]

  resources :registrations, only: [:new,:create]

  resources :dashboard, only: [:index]
  namespace :dashboard do
    resources :tasks
  end

  namespace :tasks do
    resources :completes, only: [:update]
    resources :positions, only: [:update]
  end

  namespace :stages do
    resources :positions, only: [:update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :authenticate
  end

  private
    def authenticate
      if session[:user_id] && authenticated_user = User.find(session[:user_id])
        Current.user = authenticated_user
      else
        redirect_to new_sessions_path
      end
    end
end

app/models/concerns/set_current_request_details.rb
module SetCurrentRequestDetails
  extend ActiveSupport::Concern

  included do
    before_action do
      Current.request_id = request.uuid
      Current.user_agent = request.user_agent
      Current.ip_address = request.ip
    end
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
  attribute :request_id, :user_agent, :ip_address

  resets { Time.zone = nil }

  def user=(user)
    super
  end
end

app/models/external_task_tracker.rb
class ExternalTaskTracker < ApplicationRecord
  belongs_to :task

  has_one_attached :icon
end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
  belongs_to :task

  has_one_attached :icon
end

app/models/pull_request/github.rb
class PullRequest::Github < PullRequest
end

app/models/session.rb
class Session
  include ActiveModel::Model
  attr_accessor :email, :password

  validates :email, :password, presence: true
  validate :validate_login

  def user
    @user ||= User.authenticate_by(email: email, password: password)
  end

  private
    def validate_login
      return if password.blank? || user.present?

      errors.add(:base, "Email/Password combination is incorrect")
    end
end

app/models/stage.rb
class Stage < ApplicationRecord
  include RankedModel
  ranks :row_order

  has_many :tasks, dependent: :destroy

  scope :active, -> { where(status: "active") }
  scope :paused, -> { where(status: "paused") }
  scope :backlog, -> { where(status: "backlog") }
end

app/models/task.rb
class Task < ApplicationRecord
  include RankedModel
  ranks :row_order, with_same: :stage_id

  belongs_to :user
  belongs_to :stage

  has_rich_text :notes

  has_one :pull_request, dependent: :destroy
  has_one :ticket, dependent: :destroy

  accepts_nested_attributes_for :pull_request
  accepts_nested_attributes_for :ticket

  enum priority: [:low, :medium, :high]

  validates :title, presence: true

  before_create :set_row_order

  scope :for_user, -> { where(user_id: Current.user.id) }

  scope :due, -> { where.not(due_at: nil) }
  scope :completed, -> { where.not(completed_at: nil) }
  scope :incompleted, -> { where(completed_at: nil) }

  def set_row_order
    stage.tasks.for_user.count + 1
  end

  def due_at?
    due_at.present?
  end

  def pull_request_link?
    pull_request&.link.present?
  end

  def ticket_link?
    ticket&.link.present?
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :task

  has_one_attached :icon
end

app/models/ticket/basecamp.rb
class Ticket::Basecamp < Ticket
end

app/models/ticket/linear.rb
class Ticket::Linear < Ticket
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include SetCurrentRequestDetails

  def authenticate_user
    redirect_to new_session_path if session[:user_id].nil?
  end

  def redirect_if_authenticated
    redirect_to root_path if session[:user_id]
  end
end

app/controllers/dashboard/tasks_controller.rb
module Dashboard
  class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    before_action :set_stage, only: [:new]

    def new
      @task = Task.new
      @task.build_pull_request
      @task.build_ticket
      @stage = Stage.find_by(status: params[:stage])
    end

    def create
      @task = Task.create(task_params)

      if @task.save
        redirect_to dashboard_task_path(@task), notice: "Task successfully saved"
      else
        @stage = Stage.find(task_params[:stage_id])
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @task.update(task_params)
        redirect_to dashboard_task_path(@task), notice: "Task successfully updated"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def show
    end

    def destroy
      @task.destroy

      redirect_to dashboard_index_path, notice: "Task successfully deleted"
    end

    private
      def task_params
        params
          .require(:task)
          .permit(:stage_id, :title, :priority, :due_at, :notes,
          ticket_attributes: [:id, :type, :link], pull_request_attributes: [:id, :type, :link])
          .merge(user: Current.user)
      end

      def set_task
        @task = Task.find(params[:id])
      end

      def set_stage
        @stage = Stage.find_by(status: params[:stage])
      end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @stages = Stage.rank(:row_order)
  end

  private
    attr_reader :stages
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]
  before_action :redirect_if_authenticated, only: [:new, :create]

  def new
    @form = Registration::UserForm.new
  end

  def create
    @form = Registration::UserForm.new(form_params)

    if @form.save
      session[:user_id] = @form.user.id
      Current.user = @form.user
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def form_params
    params.require(:registration_user_form).permit(:email, :username, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]
  before_action :redirect_if_authenticated, only: [:new, :create]

  def new
    @sesh = Session.new
  end

  def create
    @sesh = Session.new(session_params)

    if @sesh.valid?
      session[:user_id] = @sesh.user.id
      Current.user = User.find(session[:user_id])
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    Current.user = nil
    redirect_to new_sessions_path
  end

  private
    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/stages/positions_controller.rb
module Stages
  class PositionsController < ApplicationController
    before_action :set_stage

    def update
      @stage.update!(row_order_position: params[:row_order_position])
      head :no_content
    end

    private
      def set_stage
        @stage = Stage.find(params[:id])
      end
  end
end

app/controllers/tasks/completes_controller.rb
module Tasks
  class CompletesController < ApplicationController
    before_action :set_task, only: [:update]

    def update
      @task.update!(completed_at: Date.today)

      redirect_to dashboard_index_path, notice: "Task successfully completed"
    end

    private
      def set_task
        @task = Task.find(params[:id])
      end
  end
end

app/controllers/tasks/positions_controller.rb
module Tasks
  class PositionsController < ApplicationController
    before_action :set_task
    before_action :set_stages

    def update
      @task.update!(row_order_position: params[:row_order_position], stage_id: params[:destination_stage_id])
    end

    private
      def set_task
        @task = Task.find(params[:id])
      end

      def set_stages
        @origin_stage = Stage.find(params[:origin_stage_id])
        @destination_stage = Stage.find(params[:destination_stage_id])
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_icon(icon, classes: nil)
    classes ||= ""
    render "icons/#{icon}", classes: classes
  end
end

app/views/dashboard/tasks/_form.html.erb
<% cancel_url = local_assigns[:cancel_url] || nil %>
<% compact = local_assigns[:compact] || false %>

<%= form_with model: @task, url: submit_url, method: method, class: "space-y-6" do |f| %>
    <%= f.hidden_field :stage_id, value: @stage&.id || @task&.stage.id %>

    <%= render UI::Forms::TextField.new(form: f, field: :title, placeholder: "Add a task title", autofocus: true) %>

    <%= render UI::Forms::RadioGroup.new(label: "Priority") do %>
      <%= render UI::Forms::RadioButton.new(form: f, field: :priority, label: "Low", value: :low, checked: @task.priority == "low") %>
      <%= render UI::Forms::RadioButton.new(form: f, field: :priority, label: "Medium", value: :medium, checked: @task.priority == "medium") %>
      <%= render UI::Forms::RadioButton.new(form: f, field: :priority, label: "High", value: :high, checked: @task.priority == "high") %>
    <% end %>
    
    <%= render UI::Forms::DateField.new(form: f, field: :due_at, optional: true) %>
    
    <%= f.fields_for :ticket do |ff| %>
      <%= render UI::Forms::UrlField.new(form: ff, field: :ticket, optional: true) %>
    <% end %>
    
    <%= f.fields_for :pull_request do |ff| %>
      <%= render UI::Forms::UrlField.new(form: ff, field: :pull_request, optional: true) %>
    <% end %>

    <% if !compact %>
      <%= render UI::Forms::RichTextArea.new(form: f, field: :notes, placeholder: "Add some notes", optional: true) %>
    <% end %>

    <div class="flex gap-4 pt-6">
      <% if cancel_url %>
        <%= render UI::Links::Tertiary.new(text: "Cancel", url: cancel_url, css: "w-full") %>
      <% end %>
      <%= render UI::Buttons::Submit.new(form: f, text: "Submit", css: "w-full") %>
    </div>
<% end %>

app/views/dashboard/tasks/_notes_inline_form.html.erb
<%= form_with model: @task, url: submit_url, method: method do |f| %>
  <div class="prose prose-sm prose-indigo w-full min-w-full">
    <%= f.rich_text_area :notes, class: "block w-full min-w-fit max-w-full min-h-80 rounded-md text-gray-900 !border-none !outline-none placeholder:text-gray-400 sm:text-sm sm:leading-6", placeholder: "Add some notes", autofocus: true %>
  </div>

  <div class="flex gap-4 mt-2">
    <button type="button" data-action="inline-edit#cancel" class="flex justify-center items-center gap-1.5 w-fit rounded-md bg-white px-3 py-2 text-sm text-center font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 transition-colors hover:bg-gray-100">
      Cancel
    </button>
    <%= render UI::Buttons::Submit.new(form: f, text: "Submit", css: "w-fit") %>
  </div>
<% end %>

app/views/dashboard/tasks/edit.turbo_stream.erb
<%= turbo_stream.update "modal" do %>
  <%= render UI::Modal.new do %>
    <%= render "form", submit_url: dashboard_task_path, cancel_url: dashboard_task_path, compact: true, method: :put %>
  <% end %>
<% end %>

app/views/dashboard/tasks/new.turbo_stream.erb
<%= turbo_stream.update "modal" do %>
  <%= render UI::Modal.new do %>
    <h1 class="flex items-center gap-3 text-gray-800 text-2xl font-medium leading-4">
      <%= render_icon "list", classes: "h-7 w-7 text-indigo-600" %>
      New <%= @stage.status.capitalize %> Task
    </h1>

    <%= render "form", submit_url: dashboard_tasks_path, cancel_url: dashboard_index_path, method: :post %>
  <% end %>
<% end %>

app/views/dashboard/tasks/show.html.erb
<%= render Dashboard::Layout.new(active: :dashboard) do %>
  <div class="max-w-3xl mx-auto py-10">
    <h1 class="mb-10 text-center text-gray-800 text-2xl font-medium">
      <%= @task.title %>
    </h1>

    <div class="flex justify-between items-center">
      <%= render UI::Links::Secondary.new(text: "Tasks", icon: "arrow_left", icon_css: "w-4 h-4", url: dashboard_index_path) %>


      <div class="flex items-center gap-3">
        <%= render UI::Icons::Priority.new(priority: @task.priority, icon_css: "w-5 h-5") %>

        <% if @task.due_at? %>
          <%= render UI::Icons::DueDate.new(due_date: @task.due_at, css: "!text-sm", icon_css: "h-5 w-5") %>
        <% end %>

        <% if @task.pull_request_link? %>
          <%= render @task.pull_request, pull_request: @task.pull_request %>
        <% end %>

        <% if @task.ticket_link? %>
          <%= render @task.ticket, ticket: @task.ticket %>
        <% end %>

        <%= render UI::Links::Secondary.new(icon: "pencil", url: edit_dashboard_task_path(@task), icon_css: "w-5 h-5", turbo_frame: "modal") %>
      </div>
    </div>

    <div data-controller="inline-edit" class="w-full mt-5 mb-10 px-5 border border-indigo-100 rounded-lg">
      <div data-inline-edit-target="element">
        <% if @task.notes.present? %>
          <div class="block w-fit ml-auto pt-3 pr-2">
            <button data-action="inline-edit#edit" class="flex items-center gap-1.5 w-full rounded-lg bg-indigo-50 px-2 py-1 text-sm font-semibold text-indigo-600 shadow-sm transition-colors hover:bg-indigo-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
              Edit Notes
            </button>
          </div>
          <div class="pt-2 pb-10">
            <%= @task.notes %>
          </div>
        <% else %>
          <div class="flex justify-center items-center w-full h-60">
            <button data-action="inline-edit#edit" class="flex items-center gap-1.5 w-fit rounded-lg bg-indigo-50 px-2 py-1 text-sm font-semibold text-indigo-600 shadow-sm transition-colors hover:bg-indigo-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
              Add Notes
            </button>
          </div>
        <% end %>
      </div>

      <div data-inline-edit-target="form" class="hidden py-5">
        <%= render partial: "notes_inline_form", locals: { submit_url: dashboard_task_path, method: :put } %>
      </div>
    </div>

    <div class="flex items-center gap-3">
      <div class="w-full">
        <%= render UI::Buttons::Action.new(text: "Delete", url: dashboard_task_path(@task), method: :delete, data: { turbo_confirm: "Once deleted, the task and all associated data will be lost forever. This action cannot be undone." }, color: "red", css: "w-full py-2") %>
      </div>
      <div class="w-full">
        <%= render UI::Buttons::Action.new(text: "Complete", url: tasks_complete_path(@task), method: :put, data: { turbo: false }, color: "indigo", css: "w-full py-2") %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/ticket/basecamps/_basecamp.html.erb
<%= link_to ticket.link, target: :blank, class: "py-1 px-2 bg-amber-100 rounded-lg shadow-sm transition-colors hover:bg-amber-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-600" do %>
  <%= render_icon "basecamp", classes: "w-5 h-5 text-amber-800" %>
<% end %>

app/views/ticket/basecamps/_basecamp.html.erb
<%= link_to ticket.link, target: :blank, class: "py-1 px-2 bg-amber-100 rounded-lg shadow-sm transition-colors hover:bg-amber-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-600" do %>
  <svg class="w-4 h-4 text-amber-800" fill="currentColor" viewBox="0 0 24 24">
    <path d="M12.6516 22.453c-4.0328 0-7.575-1.5542-10.244-4.4946a1.11 1.11 0 0 1-.219-1.1338c.7008-1.8884 2.5935-6.2808 5.0205-6.2948h.0125c1.219 0 2.1312.9655 2.8648 1.7412.2192.2324.555.5875.7818.7611.5656-.5587 1.6775-2.4158 2.5422-4.2779.259-.5567.9203-.7985 1.4765-.5402.557.2584.7988.919.5404 1.4762-2.6217 5.6503-4.019 5.6503-4.478 5.6503-1.022 0-1.7628-.7843-2.4791-1.5422-.3208-.339-.9878-1.045-1.2482-1.045h-.0004c-.5665.095-1.8085 2.0531-2.6966 4.2034 2.1925 2.1722 4.9232 3.2726 8.1266 3.2726 4.3955 0 7.683-1.1964 9.0996-3.2953-.4888-5.585-3.5642-13.1634-9.0996-13.1634-4.6855 0-8.2152 3.264-10.4915 9.7007-.205.579-.8416.8828-1.4187.6776-.5789-.2047-.882-.8398-.6776-1.4185 2.624-7.421 6.859-11.1833 12.5878-11.1833 7.4826 0 10.9304 9.5613 11.3458 15.588a1.1154 1.1154 0 0 1-.1456.6314c-1.7407 3.0221-5.7182 4.6864-11.2002 4.6864Z"/>
  </svg>
<% end %>

app/views/ticket/linears/_linear.html.erb
<%= link_to ticket.link, target: :blank, class: "py-1 px-2 bg-slate-100 rounded-lg shadow-sm transition-colors hover:bg-slate-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-600" do %>
  <svg class="w-4 h-4 text-slate-700" fill="none" viewBox="0 0 100 100">
    <path fill="currentColor" d="M1.22541 61.5228c-.2225-.9485.90748-1.5459 1.59638-.857L39.3342 97.1782c.6889.6889.0915 1.8189-.857 1.5964C20.0515 94.4522 5.54779 79.9485 1.22541 61.5228ZM.00189135 46.8891c-.01764375.2833.08887215.5599.28957165.7606L52.3503 99.7085c.2007.2007.4773.3075.7606.2896 2.3692-.1476 4.6938-.46 6.9624-.9259.7645-.157 1.0301-1.0963.4782-1.6481L2.57595 39.4485c-.55186-.5519-1.49117-.2863-1.648174.4782-.465915 2.2686-.77832 4.5932-.92588465 6.9624ZM4.21093 29.7054c-.16649.3738-.08169.8106.20765 1.1l64.77602 64.776c.2894.2894.7262.3742 1.1.2077 1.7861-.7956 3.5171-1.6927 5.1855-2.684.5521-.328.6373-1.0867.1832-1.5407L8.43566 24.3367c-.45409-.4541-1.21271-.3689-1.54074.1832-.99132 1.6684-1.88843 3.3994-2.68399 5.1855ZM12.6587 18.074c-.3701-.3701-.393-.9637-.0443-1.3541C21.7795 6.45931 35.1114 0 49.9519 0 77.5927 0 100 22.4073 100 50.0481c0 14.8405-6.4593 28.1724-16.7199 37.3375-.3903.3487-.984.3258-1.3542-.0443L12.6587 18.074Z"/>
  </svg>
<% end %>